name: eosdart
description: EOSIO-based blockchain RPC API client in Dart language
version: 0.4.5
homepage: https://github.com/primes-network/eosdart
author: primes-network <primes.ntwk@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  json_annotation: ^3.0.1
  pointycastle: ^1.0.2
  eosdart_ecc:  ^0.4.3
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.7.4
  json_serializable: ^3.2.3
