name: eosdart
description: EOSIO-based blockchain RPC API client in Dart language
version: 0.4.0
homepage: https://github.com/primes-network/eosdart
author: primes-network <primes.ntwk@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0+1
  json_annotation: ^2.2.0
  pointycastle: ^1.0.1
  eosdart_ecc: ^0.3.2
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
