name: eosdart
description: EOSIO-based blockchain RPC API client in Dart language
version: 0.4.9
homepage: https://github.com/primes-network/eosdart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.3.0
  pointycastle: ^3.3.5
  eosdart_ecc: ^0.4.4
#  path: ^1.4.1

dev_dependencies:
  test: ^1.19.2
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
